export const selectOptions = {
    iva: [
        { value: '0', label: '0%' },
        { value: '3', label: '3%' },
        { value: '6', label: '6%' },
        { value: '7', label: '7%' },
        { value: '8', label: '8%' },
        { value: '9', label: '9%' },
        { value: '12', label: '12%' },
        { value: '16', label: '16%' },
        { value: '25', label: '25%' },
        { value: '26.5', label: '26.5%' },
        { value: '30', label: '30%' },
        { value: '30.4', label: '30.4%' },
        { value: '50', label: '50%' },
        { value: '53', label: '53%' },
    ],
    ieps: [
        { value: '0', label: '0%' },
        { value: '3', label: '3%' },
        { value: '6', label: '6%' },
        { value: '7', label: '7%' },
        { value: '8', label: '8%' },
        { value: '9', label: '9%' },
        { value: '12', label: '12%' },
        { value: '16', label: '16%' },
        { value: '25', label: '25%' },
        { value: '26.5', label: '26.5%' },
        { value: '30', label: '30%' },
        { value: '30.4', label: '30.4%' },
        { value: '50', label: '50%' },
        { value: '53', label: '53%' },
    ],
    isr: [
        { value: '0', label: '0%' },
        { value: '3', label: '3%' },
        { value: '6', label: '6%' },
        { value: '7', label: '7%' },
        { value: '8', label: '8%' },
        { value: '9', label: '9%' },
        { value: '12', label: '12%' },
        { value: '16', label: '16%' },
        { value: '25', label: '25%' },
        { value: '26.5', label: '26.5%' },
        { value: '30', label: '30%' },
        { value: '30.4', label: '30.4%' },
        { value: '50', label: '50%' },
        { value: '53', label: '53%' },
    ]
}